version: '3'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://GIT_DOMAIN_NAME'
        gitlab_rails['gitlab_email_from'] = 'gitlab@DOMAIN_NAME'
        gitlab_rails['gitlab_email_display_name'] = 'GitLab'
        gitlab_rails['gitlab_email_reply_to'] = 'gitlab@DOMAIN_NAME'
        gitlab_rails['backup_keep_time'] = 14515200
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "MAIL_DOMAIN_NAME"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "gitlab"
        gitlab_rails['smtp_password'] = "gitlab@DOMAIN_NAME"
        gitlab_rails['smtp_domain'] = "DOMAIN_NAME"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        nginx['listen_port'] = 443
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/ssl/certs/gitlab/server.crt"
        nginx['ssl_certificate_key'] = "/etc/ssl/certs/gitlab/server.key"
        nginx['ssl_protocols'] = "TLSv1.1 TLSv1.2"
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - ./volume_data/conf:/etc/gitlab
      - ./volume_data/ssl:/etc/ssl/certs/gitlab
      - ./volume_data/logs:/var/log/gitlab
      - ./volume_data/main:/var/opt/gitlab
