version: '3'

services:
  gitlab:
    image: gitlab/gitlab-ce:10.3.4-ce.0
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://ndss.ddns.net:3443'
        gitlab_rails['gitlab_email_from'] = 'gitlab@ndss.ddns.net'
        gitlab_rails['gitlab_email_display_name'] = 'gitlab.ndss.ddns.net'
        gitlab_rails['gitlab_email_reply_to'] = 'gitlab@ndss.ddns.net'
        gitlab_rails['backup_keep_time'] = 14515200
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "ndss.ddns.net"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "gitlab"
        gitlab_rails['smtp_password'] = "gitlab@ndss.ddns.net"
        gitlab_rails['smtp_domain'] = "ndss.ddns.net"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        unicorn['worker_timeout'] = 60
        unicorn['worker_processes'] = 3
        logging['logrotate_frequency'] = "weekly"
        logging['logrotate_rotate'] = 52
        logging['logrotate_compress'] = "compress"
        logging['logrotate_method'] = "copytruncate"
        logging['logrotate_delaycompress'] = "delaycompress"
        nginx['listen_port'] = 443
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/ssl/certs/gitlab/server.crt"
        nginx['ssl_certificate_key'] = "/etc/ssl/certs/gitlab/server.key"
        nginx['ssl_protocols'] = "TLSv1.1 TLSv1.2"
        nginx['logrotate_frequency'] = "weekly"
        nginx['logrotate_rotate'] = 52
        nginx['logrotate_compress'] = "compress"
        nginx['logrotate_method'] = "copytruncate"
        nginx['logrotate_delaycompress'] = "delaycompress"
    ports:
      - '3080:80'
      - '3443:443'
      - '3022:22'
    volumes:
      - ./volume_data/conf:/etc/gitlab
      - ./volume_data/ssl:/etc/ssl/certs/gitlab
      - ./volume_data/logs:/var/log/gitlab
      - ./volume_data/main:/var/opt/gitlab
